import {useEffect,useState} from 'react';
import {Plus,Trash2,Wallet,ArrowDownLeft,ArrowUpRight,ChartNoAxesCombined,Check,Save,Smartphone,UserRound} from 'lucide-react';
import {totals,type Budget} from './budget';
import {loadBudget,saveBudget} from './store';
type Section=keyof Budget;
const currency=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2,minimumFractionDigits:0}).format(n);
const config={income:{name:'Income',icon:ArrowDownLeft,color:'blue',unit:'Monthly amount'},expenses:{name:'Expenses',icon:ArrowUpRight,color:'orange',unit:'Monthly amount'},investment:{name:'Investment',icon:ChartNoAxesCombined,color:'purple',unit:'Account balance'}};
export default function BudgetApp({accountEmail,userId,signOut}:{accountEmail:string;userId:string;signOut:()=>void}){
const [accountOpen,setAccountOpen]=useState(false);
const [budget,setBudget]=useState<Budget|null>(null),[revision,setRevision]=useState(0),[section,setSection]=useState<Section>('expenses'),[yearly,setYearly]=useState(false),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[install,setInstall]=useState(false);
async function load(){setLoading(true);setError('');try{const d=await loadBudget(userId);setBudget(d.budget);setRevision(d.exists?1:0);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Unable to load budget');}finally{setLoading(false);}}
useEffect(()=>{load();},[userId]);
useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
function change(id:string,key:'name'|'amount',value:string){setBudget(b=>b?{...b,[section]:b[section].map(r=>r.id===id?{...r,[key]:key==='amount'?Number(value):value}:r)}:b);setDirty(true);}
function add(){setBudget(b=>b?{...b,[section]:[...b[section],{id:crypto.randomUUID(),name:section==='investment'?'New account':section==='income'?'New income':'New expense',amount:0}]}:b);setDirty(true);}
function remove(id:string){if(!window.confirm('Remove this entry? Save changes to confirm.'))return;setBudget(b=>b?{...b,[section]:b[section].filter(r=>r.id!==id)}:b);setDirty(true);}
async function save(){if(!budget)return;setSaving(true);setError('');try{await saveBudget(userId,budget,revision>0);setRevision(1);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setSaving(false);}}
const total=budget?totals(budget):{income:0,expenses:0,savings:0,investment:0},factor=yearly?12:1,settings=config[section],Icon=settings.icon;
return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-icon"><Wallet size={24}/></span><div><span className="eyebrow">MY FINANCE</span><h1>Budget</h1></div></div><div className="header-actions"><button className="account-button" aria-label="Your account" aria-expanded={accountOpen} onClick={()=>setAccountOpen(!accountOpen)}><UserRound size={18}/><span>Account</span></button><button className="install" aria-label="Add to iPhone Home Screen" onClick={()=>setInstall(!install)} aria-expanded={install}><Smartphone size={18}/><span>Add to iPhone</span></button></div></header>
{accountOpen&&<aside className="account-panel"><div><strong>Your account</strong><span>{accountEmail}</span><small>Your saved budget is separate from other users’ budgets.</small></div><button disabled={saving} onClick={()=>{if(!dirty||window.confirm('You have unsaved changes. Sign out without saving?'))signOut();}}>Sign out</button></aside>}
{install&&<aside className="install-help">Open this app in Safari. Tap Share, then <strong>Add to Home Screen</strong>. Turn on <strong>Open as Web App</strong> if shown and tap Add.</aside>}
<div className="summary-heading"><h2>Your money, at a glance</h2><div className="period" aria-label="Summary period"><button onClick={()=>setYearly(false)} aria-pressed={!yearly}>Monthly</button><button onClick={()=>setYearly(true)} aria-pressed={yearly}>Yearly</button></div></div>
<section className="summary"><div className={`savings ${total.savings<0?'negative':''}`}><span className="eyebrow">{yearly?'YEARLY':'MONTHLY'} CASH SURPLUS</span><strong>{loading?'—':currency(total.savings*factor)}</strong><p>Income minus expenses{yearly?' · monthly budget × 12':''}</p><div className="savings-rule"><span>Available after listed expenses</span><Wallet size={20}/></div></div><div className="flows"><div className="flow income"><ArrowDownLeft size={22}/><div><span>Income</span><strong>{loading?'—':currency(total.income*factor)}</strong></div></div><div className="flow expense"><ArrowUpRight size={22}/><div><span>Expenses</span><strong>{loading?'—':currency(total.expenses*factor)}</strong></div></div></div></section>
<div className="investment-strip"><span className="investment-symbol"><ChartNoAxesCombined size={23}/></span><div><span>Total investment</span><small>Current account balances</small></div><strong>{loading?'—':currency(total.investment)}</strong></div>
<section className="editor"><div className="tabs" role="tablist" aria-label="Budget entries">{(Object.keys(config) as Section[]).map(k=>{const C=config[k].icon;return <button key={k} className={config[k].color} role="tab" aria-selected={section===k} onClick={()=>setSection(k)}><C size={18}/>{config[k].name}<span>{budget?.[k].length??0}</span></button>;})}</div>
<div className="editor-heading"><div><h2><Icon size={21}/>{settings.name}</h2><p>{section==='investment'?'Enter account balances, separate from monthly cash flow.':'Enter recurring monthly amounts. Yearly totals use 12 identical months.'}</p></div><button className={`add ${settings.color}`} onClick={add} disabled={!budget||saving||(budget?.[section].length??0)>=300}><Plus size={18}/>Add {section==='investment'?'account':'entry'}</button></div>
{error&&<div className="error" role="alert">{error}{!budget&&<button onClick={load}>Try again</button>}</div>}
{loading?<div className="empty">Opening your budget…</div>:budget&&<><div className="column-head"><span>{section==='investment'?'Account':'Description'}</span><span>{settings.unit}</span><span/></div><div className="entries">{budget[section].map(r=><div className={`entry ${settings.color}`} key={r.id}><input aria-label={`${settings.name} name`} maxLength={150} value={r.name} disabled={saving} onChange={e=>change(r.id,'name',e.target.value)}/><label className="amount"><span>$</span><input aria-label={`${r.name} ${settings.unit}`} type="number" inputMode="decimal" min="0" max="1000000000000" step="0.01" disabled={saving} value={r.amount} onChange={e=>change(r.id,'amount',e.target.value)}/></label><button className="delete" aria-label={`Remove ${r.name}`} onClick={()=>remove(r.id)} disabled={saving}><Trash2 size={17}/></button></div>)}</div>{budget[section].length===0&&<div className="empty">No {settings.name.toLowerCase()} entries yet. Add your first one.</div>}<div className="section-total"><span>{section==='investment'?'Total investment':`Monthly ${settings.name.toLowerCase()}`}</span><strong>{currency(total[section])}</strong></div></>}
</section><footer className="savebar"><span role="status">{saving?'Saving…':dirty?'Unsaved changes':revision>0?<><Check size={16}/>All changes saved</>:'Ready to save your budget'}</span><button className="save" disabled={!budget||saving||(!dirty&&revision>0)} onClick={save}><Save size={18}/>{saving?'Saving…':'Save changes'}</button></footer><p className="footnote">Investment balances are a snapshot, not yearly income or monthly spending.</p></main>;
}
