import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import './styles.css';
import BudgetApp from './BudgetApp';

// Generated by sandbox or pipeline-deploy; no placeholder credentials shipped.
const configs = import.meta.glob('../amplify_outputs.json', { eager: true, import: 'default' });
const output = configs['../amplify_outputs.json'];
if (output) Amplify.configure(output as Parameters<typeof Amplify.configure>[0]);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    {!output ? <main className="auth-shell"><section className="auth-card"><h1>My Finance</h1><p>AWS configuration is not connected yet. Follow the README to deploy an Amplify backend or run a sandbox.</p></section></main> :
      <Authenticator loginMechanisms={['email']}>
        {({ user, signOut }) => <>{user && <BudgetApp key={user.userId} userId={user.userId} accountEmail={user.signInDetails?.loginId || user.username} signOut={() => signOut?.()} />}</>}
      </Authenticator>}
  </React.StrictMode>
);
